


export const COUNT = {
    ADD_COUNT: 'ADD_COUNT',
    MINUS_COUNT: 'MINUS_COUNT',
    ZERO_COUNT: 'ZERO_COUNT',
}


export const AUTH = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_REGISTER: 'AUTH_REGISTER',
}

export const USER = {
    USER_INFO_UPDATE: 'USER_INFO_UPDATE'
}